"""
FastAPI application — Meteorite Explorer backend.

Endpoints:
  GET  /api/config            — shared client/server constants (magnet radii)
  GET  /api/meteorites        — all map points (id, name, lat, lon, class, mass, year, fall)
  GET  /api/meteorites/{id}   — single meteorite detail
  GET  /api/heatmap           — S2 cell density grid for the heatmap layer
  POST /api/yield             — expected catch for a set of magnet placements
  GET  /health                — health check

Interactive docs auto-generated by FastAPI at:
  /docs           — Swagger UI
  /redoc          — ReDoc
  /openapi.json   — raw OpenAPI 3 spec
"""

import logging
from contextlib import asynccontextmanager
from typing import Literal

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from db import MAGNET_RADII_KM, get_all_points, get_conn, get_meteorite, get_s2_cells, get_yield

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("Opening warehouse...")
    get_conn()
    yield


app = FastAPI(
    title="Meteorite Explorer API",
    version="0.1.0",
    description=(
        "Backend for the supervillain magnet-placement game. Serves the "
        "NASA meteorite landings dataset (38,399 valid coordinates) plus "
        "a spatial yield calculator and S2 density grid, all read from a "
        "dbt-built DuckDB warehouse."
    ),
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health", summary="Liveness check", tags=["meta"])
def health():
    """Returns `{"status": "ok"}` if the process is up. Used by Lambda + uptime checks."""
    return {"status": "ok"}


@app.get("/api/config", summary="Shared client/server constants", tags=["meta"])
def config():
    """
    Constants the frontend needs that originate on the server. Single source
    of truth for magnet radii so the UI and the backend yield calc can't drift.
    """
    return {"magnet_radii_km": MAGNET_RADII_KM}


@app.get("/api/meteorites", summary="All meteorite landings", tags=["meteorites"])
def list_meteorites():
    """
    Every meteorite with valid coordinates (~38k rows). Shaped for the map's
    marker layer — one row per landing with lat/lon, class, mass, year, fall.
    Cached client-side; never paginated since the full set fits in memory.
    """
    return get_all_points()


@app.get(
    "/api/meteorites/{meteorite_id}",
    summary="Single meteorite by NASA id",
    tags=["meteorites"],
)
def meteorite_detail(meteorite_id: int):
    """Returns the full record for one meteorite, or 404 if the id is unknown."""
    row = get_meteorite(meteorite_id)
    if row is None:
        raise HTTPException(status_code=404, detail="Meteorite not found")
    return row


@app.get("/api/heatmap", summary="S2 cell density grid", tags=["heatmap"])
def heatmap():
    """
    Meteorites bucketed into S2 cells at level 5 (~880 occupied cells globally).
    Each row carries `count`, `total_mass_g`, `iron_mass_g`, the cell centroid,
    and the 4-vertex polygon boundary so the frontend can render the choropleth
    without an S2 library client-side.
    """
    return get_s2_cells()


class Magnet(BaseModel):
    """A single magnet placement on the map."""

    lat: float = Field(
        ge=-90,
        le=90,
        description="Latitude in decimal degrees.",
        examples=[-76.7],
    )
    lon: float = Field(
        ge=-180,
        le=180,
        description="Longitude in decimal degrees.",
        examples=[157.5],
    )
    size: Literal["S", "M", "L"] = Field(
        description=(
            "Magnet size class. Each size maps to a fixed radius in km "
            "(see GET /api/config). S=100km, M=500km, L=1500km."
        ),
        examples=["M"],
    )


class YieldRequest(BaseModel):
    """Payload for POST /api/yield."""

    magnets: list[Magnet] = Field(
        max_length=20,
        description=(
            "Up to 20 magnet placements. The yield calculation deduplicates "
            "meteorites caught by multiple overlapping magnets."
        ),
    )


@app.post(
    "/api/yield",
    summary="Expected catch for a set of magnet placements",
    tags=["yield"],
)
def yield_for_magnets(req: YieldRequest):
    """
    Runs a haversine sweep over `marts.meteorites` for each magnet, joins to
    `dim_meteorite_class` for per-class metal fractions, deduplicates landings
    caught by overlapping magnets, and returns:

    - `summary.count` — meteorites geographically within at least one magnet
    - `summary.catchable_count` — subset whose class has non-zero metal content
    - `summary.total_mass_g` — bulk mass of all caught meteorites
    - `summary.iron_mass_g` — physically meaningful magnet yield
      (sum of mass × metal_fraction_pct / 100)
    - `summary.year_range` — [first, last] year landed (or [null, null])
    - `by_class` — per-class breakdown with magnetic_tier, count, both masses
    """
    placements = [(m.lat, m.lon, MAGNET_RADII_KM[m.size]) for m in req.magnets]
    return get_yield(placements)
